filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

- module: nginx
  # Access logs
  access:
    enabled: true

  # Error logs
  error:
    enabled: true

- module: system
  # Syslog
  syslog:
    enabled: true

  # Authorization logs
  auth:
    enabled: true

- module: iptables
  log:
    enabled: true

- module: auditd
  log:
    enabled: true

- module: postgresql
  # All logs
  log:
    enabled: true

- module: suricata
  # All logs
  eve:
    enabled: true

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  # username: '${ELASTICSEARCH_USERNAME:}'
  # password: '${ELASTICSEARCH_PASSWORD:}'

xpack.monitoring.enabled: false
