version: "3.4"
services:
  elasticsearch:
    build:
      context: elasticsearch/
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    networks:
      - esnet
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./esdata1:/usr/share/elasticsearch/data:rw
  kibana:
    build:
      context: kibana/
    container_name: kibana
    depends_on:
      - elasticsearch
      - logstash
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - esnet
    ports:
      - 5601:5601
    restart: always
    volumes:
      - ./kibana/conf/kibana.yml:/usr/share/kibana/config/kibana.yml
  logstash:
    build:
      context: logstash/
    container_name: logstash
    depends_on:
      - elasticsearch
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - esnet
    ports:
      - "5044:5044"
      - "5140:5140"
      - "5140:5140/udp"
    restart: always
    volumes:
      - ./logstash/pipelines.yml:/usr/share/logstash/pipelines.yml:ro
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/:ro

volumes:
  esdata1:

networks:
  esnet:
